"""Password for User

Revision ID: 25705efd282f
Revises: 7d81e9c21138
Create Date: 2017-10-30 22:39:31.340944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25705efd282f'
down_revision = '7d81e9c21138'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###
