"""Change Password Column

Revision ID: 49331f5dd32d
Revises: 25705efd282f
Create Date: 2017-10-31 09:34:55.655161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49331f5dd32d'
down_revision = '25705efd282f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.drop_column('users', 'pass_secure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pass_secure', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
