"""Add Username Column

Revision ID: 717ad3834899
Revises: ed5ce2cd18c2
Create Date: 2017-10-31 11:28:44.615281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '717ad3834899'
down_revision = 'ed5ce2cd18c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
